services:
  chartdb:
    build:
      context: .
      dockerfile: Dockerfile
      # Optional build-time Vite variables can be provided via `--build-arg` flags if needed
    image: chartdb:local
    container_name: chartdb
    environment:
      # Runtime environment (defaults align with Dockerfile)
      NODE_ENV: production
      API_PORT: 8080
      DB_PATH: /data/chartdb.sqlite
      STATIC_DIR: /usr/src/app/dist
    ports:
      - "4567:8080"  # UI and API on same port
    volumes:
      - type: bind
        source: ./data
        target: /data
    restart: unless-stopped

# Usage:
# 1) docker compose up --build
# 2) Open http://localhost:4567 for the UI; API is at http://localhost:4567/api
# Persisted SQLite database will be stored under ./data/chartdb.sqlite
